In [1]:
import torch

In [2]:
length=5
d = 20

In [3]:
nu = torch.arange(0, length).unsqueeze(-1)
print(nu, nu.shape)

tensor([[0],
        [1],
        [2],
        [3],
        [4]]) torch.Size([5, 1])


In [4]:
de = torch.pow(1000, torch.arange(0, d, 2) / d).unsqueeze(0) # 1000^(2j/d)
print(de, de.shape)

tensor([[  1.0000,   1.9953,   3.9811,   7.9433,  15.8489,  31.6228,  63.0957,
         125.8925, 251.1887, 501.1872]]) torch.Size([1, 10])


In [5]:
w = nu / de
print(w, w.shape)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.0000e+00, 5.0119e-01, 2.5119e-01, 1.2589e-01, 6.3096e-02, 3.1623e-02,
         1.5849e-02, 7.9433e-03, 3.9811e-03, 1.9953e-03],
        [2.0000e+00, 1.0024e+00, 5.0238e-01, 2.5179e-01, 1.2619e-01, 6.3246e-02,
         3.1698e-02, 1.5887e-02, 7.9621e-03, 3.9905e-03],
        [3.0000e+00, 1.5036e+00, 7.5357e-01, 3.7768e-01, 1.8929e-01, 9.4868e-02,
         4.7547e-02, 2.3830e-02, 1.1943e-02, 5.9858e-03],
        [4.0000e+00, 2.0047e+00, 1.0048e+00, 5.0357e-01, 2.5238e-01, 1.2649e-01,
         6.3396e-02, 3.1773e-02, 1.5924e-02, 7.9811e-03]]) torch.Size([5, 10])


In [6]:
sinw = torch.sin(w)
cosw = torch.cos(w)
print(sinw, sinw.shape)
print(cosw, cosw.shape)

tensor([[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000],
        [ 0.8415,  0.4805,  0.2486,  0.1256,  0.0631,  0.0316,  0.0158,  0.0079,
          0.0040,  0.0020],
        [ 0.9093,  0.8428,  0.4815,  0.2491,  0.1259,  0.0632,  0.0317,  0.0159,
          0.0080,  0.0040],
        [ 0.1411,  0.9977,  0.6842,  0.3688,  0.1882,  0.0947,  0.0475,  0.0238,
          0.0119,  0.0060],
        [-0.7568,  0.9073,  0.8440,  0.4826,  0.2497,  0.1262,  0.0634,  0.0318,
          0.0159,  0.0080]]) torch.Size([5, 10])
tensor([[ 1.0000,  1.0000,  1.0000,  1.0000,  1.0000,  1.0000,  1.0000,  1.0000,
          1.0000,  1.0000],
        [ 0.5403,  0.8770,  0.9686,  0.9921,  0.9980,  0.9995,  0.9999,  1.0000,
          1.0000,  1.0000],
        [-0.4161,  0.5383,  0.8764,  0.9685,  0.9920,  0.9980,  0.9995,  0.9999,
          1.0000,  1.0000],
        [-0.9900,  0.0672,  0.7293,  0.9295,  0.9821,  0.9955,  0.9989,  0.9997,
          0.9999,  1.0000]

In [7]:
encoding_matrix = torch.zeros(length, d)
print(encoding_matrix, encoding_matrix.shape)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]) torch.Size([5, 20])


In [8]:
encoding_matrix[:,0::2] = sinw
print(encoding_matrix, encoding_matrix.shape)

tensor([[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.8415,  0.0000,  0.4805,  0.0000,  0.2486,  0.0000,  0.1256,  0.0000,
          0.0631,  0.0000,  0.0316,  0.0000,  0.0158,  0.0000,  0.0079,  0.0000,
          0.0040,  0.0000,  0.0020,  0.0000],
        [ 0.9093,  0.0000,  0.8428,  0.0000,  0.4815,  0.0000,  0.2491,  0.0000,
          0.1259,  0.0000,  0.0632,  0.0000,  0.0317,  0.0000,  0.0159,  0.0000,
          0.0080,  0.0000,  0.0040,  0.0000],
        [ 0.1411,  0.0000,  0.9977,  0.0000,  0.6842,  0.0000,  0.3688,  0.0000,
          0.1882,  0.0000,  0.0947,  0.0000,  0.0475,  0.0000,  0.0238,  0.0000,
          0.0119,  0.0000,  0.0060,  0.0000],
        [-0.7568,  0.0000,  0.9073,  0.0000,  0.8440,  0.0000,  0.4826,  0.0000,
          0.2497,  0.0000,  0.1262,  0.0000,  0.0634,  0.0000,  0.0318,  0.0000,
      

In [9]:
encoding_matrix[:,1::2] = cosw
print(encoding_matrix, encoding_matrix.shape)

tensor([[ 0.0000,  1.0000,  0.0000,  1.0000,  0.0000,  1.0000,  0.0000,  1.0000,
          0.0000,  1.0000,  0.0000,  1.0000,  0.0000,  1.0000,  0.0000,  1.0000,
          0.0000,  1.0000,  0.0000,  1.0000],
        [ 0.8415,  0.5403,  0.4805,  0.8770,  0.2486,  0.9686,  0.1256,  0.9921,
          0.0631,  0.9980,  0.0316,  0.9995,  0.0158,  0.9999,  0.0079,  1.0000,
          0.0040,  1.0000,  0.0020,  1.0000],
        [ 0.9093, -0.4161,  0.8428,  0.5383,  0.4815,  0.8764,  0.2491,  0.9685,
          0.1259,  0.9920,  0.0632,  0.9980,  0.0317,  0.9995,  0.0159,  0.9999,
          0.0080,  1.0000,  0.0040,  1.0000],
        [ 0.1411, -0.9900,  0.9977,  0.0672,  0.6842,  0.7293,  0.3688,  0.9295,
          0.1882,  0.9821,  0.0947,  0.9955,  0.0475,  0.9989,  0.0238,  0.9997,
          0.0119,  0.9999,  0.0060,  1.0000],
        [-0.7568, -0.6536,  0.9073, -0.4205,  0.8440,  0.5363,  0.4826,  0.8759,
          0.2497,  0.9683,  0.1262,  0.9920,  0.0634,  0.9980,  0.0318,  0.9995,
      

In [24]:
t = torch.randint(1, length+1, (length,))
print(t, t.shape)

tensor([1, 1, 2, 1, 2]) torch.Size([5])


In [26]:
output = encoding_matrix[t, ...]
print(output, output.shape)

tensor([[ 0.8415,  0.5403,  0.4805,  0.8770,  0.2486,  0.9686,  0.1256,  0.9921,
          0.0631,  0.9980,  0.0316,  0.9995,  0.0158,  0.9999,  0.0079,  1.0000,
          0.0040,  1.0000,  0.0020,  1.0000],
        [ 0.8415,  0.5403,  0.4805,  0.8770,  0.2486,  0.9686,  0.1256,  0.9921,
          0.0631,  0.9980,  0.0316,  0.9995,  0.0158,  0.9999,  0.0079,  1.0000,
          0.0040,  1.0000,  0.0020,  1.0000],
        [ 0.9093, -0.4161,  0.8428,  0.5383,  0.4815,  0.8764,  0.2491,  0.9685,
          0.1259,  0.9920,  0.0632,  0.9980,  0.0317,  0.9995,  0.0159,  0.9999,
          0.0080,  1.0000,  0.0040,  1.0000],
        [ 0.8415,  0.5403,  0.4805,  0.8770,  0.2486,  0.9686,  0.1256,  0.9921,
          0.0631,  0.9980,  0.0316,  0.9995,  0.0158,  0.9999,  0.0079,  1.0000,
          0.0040,  1.0000,  0.0020,  1.0000],
        [ 0.9093, -0.4161,  0.8428,  0.5383,  0.4815,  0.8764,  0.2491,  0.9685,
          0.1259,  0.9920,  0.0632,  0.9980,  0.0317,  0.9995,  0.0159,  0.9999,
      